# This file can be used with the VSCode REST Client extension
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
# It allows you to make REST calls from within your editor,
# so you don't need postman / insomnia for quick debugging

###

# @name listIndex
GET {{host}}/indexes
X-Meili-API-Key: {{key}}

###

# @name getKeys
GET {{host}}/keys
X-Meili-API-Key: {{key}}

###

# @name dropindex
DELETE {{host}}/indexes/books
X-Meili-API-Key: {{key}}

###

# @name createIndex
POST {{host}}/indexes
X-Meili-API-Key: {{key}}
content-type: application/json

{
    "uid": "test",
    "primaryKey": "id"
}

###

# @name createDoc
POST {{host}}/indexes/test/documents
X-Meili-API-Key: {{key}}
content-type: application/json

[
    {
        "id": 1,
        "text": "first test"
    },
    {
        "id": 1,
        "text": "second test"
    }
]

###

# @name stats
GET {{host}}/indexes/test/stats
X-Meili-API-Key: {{key}}

###

# @name updatestopwords
POST {{host}}/indexes/test/settings/stop-words
X-Meili-API-Key: {{key}}
content-type: application/json

[
		"the", "an", "a",
		"de", "het", "een",
		"le", "la", "les"
]

###

# @name getUpdateStatus
GET {{host}}/indexes/test/updates/0
X-Meili-API-Key: {{key}}

###

# @name search
GET {{host}}/indexes/test/search?q=test
X-Meili-API-Key: {{key}}
